name: getx_clean_architecture_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  get: 4.6.5
  get_storage: ^2.1.1
  logger: ^1.3.0
  skeletons: ^0.0.3
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  assets:
    - assets/
    - assets/images/

  uses-material-design: true
